apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-service
  labels:
    app: worker-service
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: worker-service
  template:
    metadata:
      labels:
        app: worker-service
    spec:
      containers:
      - name: worker-service
        image: codepulse-worker:latest
        imagePullPolicy: Never
        env:
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: codepulse-secrets
              key: GEMINI_API_KEY
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: codepulse-secrets
              key: DATABASE_URL
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-service:9092"